//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Phones = new HashSet<Phone>();
            this.Addresses = new HashSet<Address>();
        }
    
        public int PersonID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
    
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual PersonInfo PersonInfoes { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
