// <autogenerated>
//   This file was generated by T4 code generator TrackableEntitiesServer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace TrackableEntitiesDTO.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;

    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class Address : ITrackable
    {
        public Address()
        {
            this.People = new List<Person>();
        }//ctor

        [DataMember]
        public int AddressID  { get; set; }

        [DataMember]
        public string Address1  { get; set; }

        [DataMember]
        public string Address2  { get; set; }

        [DataMember]
        public string Address3  { get; set; }

        [DataMember]
        public string City  { get; set; }

        [DataMember]
        public string Country  { get; set; }

        [DataMember]
        public string Postcode  { get; set; }

        [DataMember]
        public ICollection<Person> People  { get; set; }

        [DataMember]
        public TrackingState TrackingState { get; set; }

        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }

    } //Class
} //Namespace
