// <autogenerated>
//   This file was generated by T4 code generator TrackableEntitiesServer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace TrackableEntitiesDTO.Mapping
{
    using System.Data.Entity.ModelConfiguration;
    using TrackableEntitiesDTO.Entities;

    public partial class AddressMap : EntityTypeConfiguration<Address>
    {
        public AddressMap()
        {
            // Primary Key
             this.HasKey(t => t.AddressID);
        
            //Properties
            this.Property(t => t.Address1)
                .IsRequired();

            this.Property(t => t.Address2)
                .IsRequired();

            this.Property(t => t.Address3)
                .IsRequired();

            this.Property(t => t.City)
                .IsRequired();

            this.Property(t => t.Country)
                .IsRequired();

            this.Property(t => t.Postcode)
                .IsRequired();

            // Table & Column Mappings
            this.ToTable("Addresses");
            this.Property(t => t.AddressID).HasColumnName("AddressID");
            this.Property(t => t.Address1).HasColumnName("Address1");
            this.Property(t => t.Address2).HasColumnName("Address2");
            this.Property(t => t.Address3).HasColumnName("Address3");
            this.Property(t => t.City).HasColumnName("City");
            this.Property(t => t.Country).HasColumnName("Country");
            this.Property(t => t.Postcode).HasColumnName("Postcode");

            // Tracking Properties
            this.Ignore(t => t.TrackingState);
            this.Ignore(t => t.ModifiedProperties);

            // Relationships and Foreign Keys - if any
            // End Relationships and Foreign Keys

        }//ctor end
    }//Class end
}// Namespace end
