// <autogenerated>
//   This file was generated by T4 code generator TrackableEntitiesServer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace TrackableEntitiesDTO
{
    using System;
    using System.Data.Entity;
    using TrackableEntitiesDTO.Entities;
    using TrackableEntitiesDTO.Mapping;

    public partial class Model1Container : DbContext
    {
        static Model1Container()
        {
            Database.SetInitializer<Model1Container>(null);
        }

        public Model1Container() : base("Name=Model1Container")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }

         public DbSet<Person> People { get; set; }
         public DbSet<Phone> Phones { get; set; }
         public DbSet<PersonInfo> PersonInfoes { get; set; }
         public DbSet<Address> Addresses { get; set; }
 
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new PersonMap());
            modelBuilder.Configurations.Add(new PhoneMap());
            modelBuilder.Configurations.Add(new PersonInfoMap());
            modelBuilder.Configurations.Add(new AddressMap());
        }

    } //Class
} //Namespace
