// <autogenerated>
//   This file was generated by T4 code generator TrackableEntitiesServer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace TrackableEntitiesDTO.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;

    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class Person : ITrackable
    {
        public Person()
        {
            this.Phones = new List<Phone>();
            this.Addresses = new List<Address>();
        }//ctor

        [DataMember]
        public int PersonID  { get; set; }

        [DataMember]
        public string Firstname  { get; set; }

        [DataMember]
        public string Lastname  { get; set; }

        [DataMember]
        public ICollection<Phone> Phones  { get; set; }

        [DataMember]
        public PersonInfo PersonInfoes { get; set; }

        [DataMember]
        public ICollection<Address> Addresses  { get; set; }

        [DataMember]
        public TrackingState TrackingState { get; set; }

        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }

    } //Class
} //Namespace
