// <autogenerated>
//   This file was generated by T4 code generator TrackableEntitiesServer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace TrackableEntitiesDTO.Mapping
{
    using System.Data.Entity.ModelConfiguration;
    using TrackableEntitiesDTO.Entities;

    public partial class PersonMap : EntityTypeConfiguration<Person>
    {
        public PersonMap()
        {
            // Primary Key
             this.HasKey(t => t.PersonID);
        
            //Properties
            this.Property(t => t.Firstname)
                .IsRequired();

            this.Property(t => t.Lastname)
                .IsRequired();

            // Table & Column Mappings
            this.ToTable("People");
            this.Property(t => t.PersonID).HasColumnName("PersonID");
            this.Property(t => t.Firstname).HasColumnName("Firstname");
            this.Property(t => t.Lastname).HasColumnName("Lastname");

            // Tracking Properties
            this.Ignore(t => t.TrackingState);
            this.Ignore(t => t.ModifiedProperties);

            // Relationships and Foreign Keys - if any
            // There are 1 M:M(s)
            // There are 0 FK(s)
            //-- Start Many to Many
            this.HasMany(t => t.Addresses)
                .WithMany(t => t.People)
                .Map(m =>
                 {
                    m.ToTable("PersonAddress");
                    m.MapLeftKey("People_PersonID");
                    m.MapRightKey("Addresses_AddressID");
                });
            //-- End Many to Many
            //-- Start Foreign Key        
            //-- End Foreign Key 
                
            // End Relationships and Foreign Keys

        }//ctor end
    }//Class end
}// Namespace end
