// <autogenerated>
//   This file was generated by T4 code generator TrackableEntitiesServer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace TrackableEntitiesDTO.Mapping
{
    using System.Data.Entity.ModelConfiguration;
    using TrackableEntitiesDTO.Entities;

    public partial class PersonInfoMap : EntityTypeConfiguration<PersonInfo>
    {
        public PersonInfoMap()
        {
            // Primary Key
             this.HasKey(t => t.PersonID);
        
            //Properties
            this.Property(t => t.Data1)
                .IsRequired();

            this.Property(t => t.Data2)
                .IsRequired();

            // Table & Column Mappings
            this.ToTable("PersonInfoes");
            this.Property(t => t.PersonID).HasColumnName("PersonID");
            this.Property(t => t.Data1).HasColumnName("Data1");
            this.Property(t => t.Data2).HasColumnName("Data2");

            // Tracking Properties
            this.Ignore(t => t.TrackingState);
            this.Ignore(t => t.ModifiedProperties);

            // Relationships and Foreign Keys - if any
            // End Relationships and Foreign Keys

        }//ctor end
    }//Class end
}// Namespace end
