// <autogenerated>
//   This file was generated by T4 code generator TrackableEntitiesServer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace TrackableEntitiesDTO.Mapping
{
    using System.Data.Entity.ModelConfiguration;
    using TrackableEntitiesDTO.Entities;

    public partial class PhoneMap : EntityTypeConfiguration<Phone>
    {
        public PhoneMap()
        {
            // Primary Key
             this.HasKey(t => t.PhoneID);
        
            //Properties
            this.Property(t => t.PhoneNumber)
                .IsRequired();

            // Table & Column Mappings
            this.ToTable("Phones");
            this.Property(t => t.PhoneID).HasColumnName("PhoneID");
            this.Property(t => t.PersonID).HasColumnName("PersonID");
            this.Property(t => t.PhoneNumber).HasColumnName("PhoneNumber");

            // Tracking Properties
            this.Ignore(t => t.TrackingState);
            this.Ignore(t => t.ModifiedProperties);

            // Relationships and Foreign Keys - if any
            // There are 0 M:M(s)
            // There are 1 FK(s)
            //-- Start Many to Many
            //-- End Many to Many
            //-- Start Foreign Key        
            this.HasRequired(t => t.Person)
                .WithMany(t => t.Phones)
                .HasForeignKey(d => d.PersonID);
            //-- End Foreign Key 
                
            // End Relationships and Foreign Keys

        }//ctor end
    }//Class end
}// Namespace end
