// <autogenerated>
//   This file was generated by T4 code generator TrackableEntitiesServer.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace TrackableEntitiesDTO.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;

    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class Phone : ITrackable
    {
        public Phone()
        {
        }//ctor

        [DataMember]
        public int PhoneID  { get; set; }

        [DataMember]
        public int PersonID  { get; set; }

        [DataMember]
        public string PhoneNumber  { get; set; }

        [DataMember]
        public Person Person { get; set; }

        [DataMember]
        public TrackingState TrackingState { get; set; }

        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }

    } //Class
} //Namespace
